server:
  port: 16000
spring:
  application:
    name: "bussiness-serve"
eureka:
  instance:
    prefer-ip-address: true
    instance-id: "bussiness-serve01"
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    service-url:
      defaultZone: "http://eurekaServer18000:18000/eureka/,http://eurekaServer18001:18001/eureka/"